name: Android Build and Release

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    env:
      ANDROID_KEYSTORE_PROPERTIES: ${{ secrets.ANDROID_KEYSTORE_PROPERTIES }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install npm dependencies
        run: |
          npm install
          cd android && ./gradlew wrapper

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Restore signing properties
        run: |
          echo "$ANDROID_KEYSTORE_PROPERTIES" | base64 -d > android/keystore.properties
          grep "MYAPP" android/keystore.properties || echo "Properties loaded"

      - name: Build Release APK
        working-directory: ./android
        run: ./gradlew assembleRelease

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: release-$(date +'%Y-%m-%d-%H-%M-%S')
          name: Release $(date +'%Y-%m-%d %H:%M:%S')
          draft: false
          prerelease: false
          generate_release_notes: true

      - name: Upload Release APK
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: android/app/build/outputs/apk/release/app-release.apk

      - name: Cleanup
        run: rm -f android/keystore.properties