name: Android Build and Release

on:
  push:
    branches:
      - main
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install npm dependencies
        run: npm install

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Decode Android Keystore
        run: |
              echo "${{ secrets.MYAPP_KEYSTORE }}" | base64 -d > android/app/key.jks
    
      - name: Create key.properties
        run: |
              echo "storePassword=${{ secrets.MYAPP_UPLOAD_STORE_PASSWORD }}" > android/key.properties
              echo "keyPassword=${{ secrets.MYAPP_UPLOAD_KEY_PASSWORD }}" >> android/key.properties
              echo "keyAlias=${{ secrets.MYAPP_UPLOAD_KEY_ALIAS }}" >> android/key.properties
              echo "storeFile=key.jks" >> android/key.properties

      - name: Build Release APK
        working-directory: ./android
        run: ./gradlew assembleRelease
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: android/app/build/outputs/apk/release/app-release.apk
      - name: Rename APK
        run: mv android/app/build/outputs/apk/release/app-release.apk android/app/build/outputs/apk/release/younus-app.apk
        

      - name: Create GitHub Release and Upload APK
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ github.run_number }}
          name: "Release v${{ github.run_number }}"
          artifacts: android/app/build/outputs/apk/release/younus-app.apk
          token: ${{ secrets.GITHUB_TOKEN }}